name: Python Scheduled Task

on:
  schedule:
    - cron: "*/15 * * * *"  # Run every 15 minutes
  workflow_dispatch:  # Allows for manual triggering

jobs:
  download_and_extract_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/data/BoM/requirements.txt

      - name: Run Python script and log output
        run: |
          python .github/workflows/getBoM_FTP.py >> output.log 2>&1  # Append both stdout and stderr to output.log

      - name: Commit changes to a temporary branch
        run: |
          git config --global user.name "enSea00"
          git config --global user.email "nbcart@hotmail.com"
          git checkout -b temp-branch
          git add IDQ60910.tgz output.log
          git commit -m "Add downloaded file and log"
          git push origin temp-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Add downloaded file and log"
          body: "This PR adds the downloaded file and log generated by the script."
          base: main
          head: temp-branch
