name: Download TGZ File

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current working directory
        run: |
          pwd  # This will print the path of the current directory
          ls -l  # This will list the files in the current directory to ensure the .tgz file is there

      - name: Download TGZ file from public FTP
        run: |
          curl -o IDQ60910.tgz "ftp://ftp.bom.gov.au/anon/gen/fwo/IDQ60910.tgz"

      - name: Check if TGZ file was downloaded
        run: |
          if [ ! -f "IDQ60910.tgz" ]; then
            echo "TGZ file not downloaded, exiting."
            exit 1  # Exit the workflow if the file is not found
          elif [ ! -s "IDQ60910.tgz" ]; then
            echo "TGZ file is empty, exiting."
            exit 1  # Exit the workflow if the file is empty
          else
            echo "TGZ file successfully downloaded."
          fi

      - name: List contents of TGZ file (before extraction)
        run: |
          echo "Listing contents of the TGZ file:"
          tar -tzf IDQ60910.tgz  # List files inside the archive

      - name: Extract all contents (debugging extraction)
        run: |
          mkdir extracted
          tar -xzf IDQ60910.tgz -C extracted  # Extract everything first to check content

      - name: List all extracted files
        run: |
          echo "Listing all files extracted from the TGZ:"
          ls -R extracted  # List files recursively, including in subdirectories

      - name: Collate JSON files into one master.json
        run: |
          # Initialize an empty JSON array
          echo "[]" > extracted/master.json
          
          # Loop through all JSON files and merge them into master.json
          for file in extracted/*.json; do
            echo $file
            # Check if the file is empty before trying to merge
            if [ -s "$file" ]; then
              jq -s '.[0] + .[1]' extracted/master.json "$file" > temp.json && mv temp.json extracted/master.json
            else
              echo "Skipping empty file: $file"
            fi
          done

      - name: Upload master.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: master-json-file
          path: extracted/master.json

      - name: Commit master.json to repository
        run: |
          git config --global user.name "enSea00"
          git config --global user.email "nbcart@hotmail.com"
          mv extracted/master.json .github/workflows/data/BoM/
          git add .github/workflows/data/BoM/master.json
          git commit -m "Add collated master.json file"
          git push
